# Generated by Django 2.2.16 on 2022-11-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221111_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='title',
        ),
    ]
