# Generated by Django 2.2.16 on 2022-11-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221112_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
    ]
